apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cniep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cniep
subjects:
- kind: ServiceAccount
  name: cniep
  namespace: cniep
