apiVersion: v1
kind: ServiceAccount
metadata:
  name: cniep
  annotations:
    #add this annotations to use eks k8s iam openid connect identity provider
    #https://docs.aws.amazon.com/eks/latest/userguide/authenticate-oidc-identity-provider.html
    #https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
    eks.amazonaws.com/role-arn: arn:aws:iam::{aws account id}:role/{IAM role}
    
