apiVersion: v1
kind: Service
metadata:
  labels:
    app: cniep
  name: cniep
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: cniep
  sessionAffinity: None
  type: ClusterIP
